// TODO ACTIONS
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const EDIT_TODO_ITEM = "EDIT_TODO_ITEM";
export const IS_COMPLETED = "IS_COMPLETED";

// TODO CONTROLS ACTIONS
export const ACTION_CHANGED = "ACTION_CHANGED";
export const MARK_ALL_COMPLETED = "MARK_ALL_COMPLETED";
export const MARK_ALL_INCOMPLETED = "MARK_ALL_INCOMPLETED";



